lives = input("Please enter the number of lives.")
lives = int(lives)
print()
energy = input("Please enter the energy level")
energy = int(energy)
print()
sheild = input("Please enter the shield level")
sheild = int(sheild)
print()
print("Health has been set")
print()
print("Lives:", lives* (u"\u2661"))
print("Energy:", energy* (u"\u2666"))
print("Sheild:", sheild* (u"\u2666"))
